// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 12:15:47 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/kunhernowoputra/claude/sort-smart/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/plugins/**/*.{js,ts,mjs}","/Users/kunhernowoputra/claude/sort-smart/app/composables/**/*.{js,ts,mjs}","/Users/kunhernowoputra/claude/sort-smart/app/utils/**/*.{js,ts,mjs}","/Users/kunhernowoputra/claude/sort-smart/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kunhernowoputra/claude/sort-smart/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;